#!/usr/bin/env bash

# XDG base directory
# More info on --> https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
export XDG_CACHE_HOME=~/.cache
export XDG_CONFIG_HOME=~/.config
export XDG_DATA_HOME=~/.local/share
export NIXED=$XDG_CONFIG_HOME/nixed
export PYTHONPATH=$XDG_CONFIG_HOME/pip
export DENO_INSTALL_ROOT=$XDG_CONFIG_HOME/deno

# X11
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
export XSERVERRC="$XDG_CONFIG_HOME/X11/xserverrc"
export XCOMPOSEFILE="$XDG_CONFIG_HOME"/X11/xcompose
export XCOMPOSECACHE="$XDG_CACHE_HOME"/X11/xcompose

# Applications
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export HISTFILE="$XDG_DATA_HOME/bash/history"
export GTK_RC_FILES="$XDG_CONFIG_HOME/gtk-1.0/gtkrc"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc

# Add folder to your path
# Note don't forgot to include `:` in end before entering next folder path
export PATH="
$PATH:
~/.local/bin:
$XDG_CONFIG_HOME/npm/bin:
$XDG_CONFIG_HOME/deno/bin
"
